---
# 只适用于agent/snmp接口类型的数据巡检，不支持web监控等其他方式

# 日志级别
logging: debug
logfile: monitor_hosts_inspect.log


# 巡检指标映射值
inspect_map:
  - type: 1  # 1: agent类型
    key: "system.cpu.util[,idle,avg5]"
  - type: 2  # 2： snmp类型
    key: "sysDescr"


# 关联发件人方式 proxy/server/group,如果选择proxy和group分发，建议仅配置一个zbabix数据源
# proxy: 以proxy为key,通过配置指定proxy发送给指定人员
# group: 以group为key,通过配置指定group发送给指定人员
# server: 以server为key,通过配置指定group发送给指定人员
related_key: proxy

# zabbix数据源配置,name需要保证唯一性,避免奇怪问题产生
datasource:
  server:
    - name: "idc_zabbix"
      url: "http://10.12.66.107"
      user: "wangwei"
      password: "aspire@1qaz2wsx"

#    - name: "cloud_zabbix"
#      url: "http://120.25.168.251:8989"
#      user: "Admin"
#      password: "aspire@1qaz2wsx"
#
#    - name: "cloud_zabbix2"
#      url: "http://120.25.168.251:8989"
#      user: "Admin"
#      password: "aspire@1qaz2wsx"

# smtp发件服务器配置
smtp_from: "zabbix@sz.mail"
smtp_server: 10.1.9.82

# 收件人配置
receivers:
  - name: "北京xxxx"      # 邮件标题关键字
    related_value: []   # 收件人关联信息, 如果related_key为proxy, 需要填代理数据(无需区分大小写)；如果为group需要为主机群组数据
    emails: []            # 收件邮箱
