---
# 日志级别
logging: debug
logfile: monitor_metrics.log
#loghanler: monitor_metrics_logs


# zabbix数据源配置
datasource:
  server:
    - name: "idc_zabbix"
      url: "http://10.12.66.107"
      user: "wangwei"
      password: "aspire@1qaz2wsx"

    - name: "cloud_zabbix"
      url: "http://120.25.168.251:8989"
      user: "Admin"
      password: "aspire@1qaz2wsx"

# kafka集群地址

bootstrap_servers: ["10.12.70.42:9092"]
topic: "zabbix"


excluding_metrics_type:
  - 17  # SNMP trap;
  - 9  #  web item
  - 5