---
# 日志级别
logging: debug
logfile: proxy_connect_server.log

# zabbix_proxy与server连接超时时间(s)
timeout: 300

zabbix:
  host: "10.12.66.107"
  user: "wangwei"
  password: "aspire@1qaz2wsx"

# 映射到zabbix的主机和zabbix_sender发送的指定地址
map_host: 10.12.66.107
map_proxy: 10.12.7.103
map_port: 10051
# 映射模板键值，一般不需要修改,如修改
key: "proxy_data"


